+6 samples/demos
DeCenter-AI/decenter-ai.streamlit.app pull request #64
Opened 2023-10-19 22:19 UTC by Dineshjnld

## Related Issue(s)

[//]:
  #
  "[Cite any related issue(s) or feature request(s) from the repository's issue tracker.]"

Fixes # For #

## Proposed Changes

[//]: # '[List down the specific changes you have made in this pull request.]'

- [x]
- [x]

## Checklist

- [x] I have followed the repository's contribution guidelines.
- [x] I have added necessary documentation or updated existing documentation.
- [x] My code follows the established code style and formatting of the project.
- [x] I have tested my changes and they function as expected.
- [x] I have added suitable unit tests (if applicable).

## Screenshots
<img width="288" alt="image" src="https://github.com/DeCenter-AI/decenter-ai.streamlit.app/assets/106725225/6ac3f0fd-611a-442d-9542-63f54b3e5c40">

## To-Do

- [ ]

## Additional Information

2023-10-20 03:06 UTC, Nasfame requested changes

2023-10-20 03:06 UTC, Nasfame commented on samples/demos/Naive-Bayes.zip
rename to naive-bayes.zip

2023-10-20 03:06 UTC, Nasfame commented on samples/demos/inference-example.zip
rename more appropriate. This is too unclear

2023-10-20 03:07 UTC, Nasfame requested changes

2023-10-20 03:07 UTC, Nasfame commented on samples/demos/winequality-red.zip
rename: the demo is not clear

2023-10-20 20:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DeCenter-AI/decenter-ai.streamlit.app?pullRequest=64) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/DeCenter-AI/decenter-ai.streamlit.app?pullRequest=64) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DeCenter-AI/decenter-ai.streamlit.app?pullRequest=64) it.</sub>

2023-10-20 20:28 UTC, Nasfame commented on samples/demos/Naive-Bayes.zip
@Dineshjnld any updates on this

2023-10-21 19:56 UTC, Nasfame commented
@Dineshjnld sign the cla

2023-10-21 19:57 UTC, Nasfame commented
@Dineshjnld update the branch

2023-10-21 19:57 UTC, Nasfame commented
```
git fetch origin
git merge origin/main
```

2023-10-25 06:25 UTC, Nasfame commented
Fixes #63

2023-10-26 18:14 UTC, Dineshjnld reviewed
done, but tests are failing?

2023-10-26 18:25 UTC, Dineshjnld reviewed
1

2023-10-26 18:32 UTC, Dineshjnld reviewed
.

2023-10-26 19:19 UTC, Nasfame approved these changes
LGTM

2023-10-26 19:19 UTC, merged